# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-15 22:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyetracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gathereddata',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
