# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-14 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyetracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gathereddata',
            name='gaze',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gathereddata',
            name='incident',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gathereddata',
            name='speed',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gathereddata',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
