# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-15 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eyetracking', '0002_auto_20160314_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gathereddata',
            name='user',
        ),
    ]
