# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-15 18:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eyetracking', '0003_remove_gathereddata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gathereddata',
            name='title',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 15, 18, 6, 22, 520536, tzinfo=utc)),
        ),
    ]
