# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-15 18:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eyetracking', '0004_gathereddata_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gathereddata',
            name='title',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 15, 18, 10, 6, 709701, tzinfo=utc)),
        ),
    ]
