# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-15 23:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eyetracking', '0004_auto_20160315_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gathereddata',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
