# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-12 21:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eyetracking', '0005_collecteddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='collecteddate',
            name='imported_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 12, 21, 23, 33, 731965, tzinfo=utc)),
        ),
    ]
