# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyetracking', '0007_auto_20160321_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('boston_temp', models.DecimalField(decimal_places=1, max_digits=5)),
                ('houston_temp', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
    ]
