# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-12 21:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eyetracking', '0007_auto_20160312_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collecteddate',
            old_name='category',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='collecteddate',
            name='imported_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 12, 21, 25, 40, 348640, tzinfo=utc)),
        ),
    ]
