# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-12 21:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eyetracking', '0008_auto_20160312_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_date', models.DateTimeField(default=datetime.datetime(2016, 3, 12, 21, 26, 45, 944356, tzinfo=utc))),
                ('imported_data', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eyetracking.UserProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='collecteddate',
            name='user',
        ),
        migrations.DeleteModel(
            name='CollectedDate',
        ),
    ]
