# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-12 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyetracking', '0010_auto_20160312_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='collecteddata',
            name='numerical_data',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='imported_date',
            field=models.DateTimeField(default='django.utils.timezone.now()'),
        ),
    ]
