# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-12 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eyetracking', '0011_auto_20160312_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collecteddata',
            name='imported_data',
        ),
        migrations.RemoveField(
            model_name='collecteddata',
            name='numerical_data',
        ),
    ]
