# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-12 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eyetracking', '0012_auto_20160312_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collecteddata',
            name='user',
        ),
        migrations.DeleteModel(
            name='CollectedData',
        ),
    ]
