# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-28 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eyetracking', '0012_auto_20160328_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gathereddata',
            name='graph',
            field=models.OneToOneField(default='hello', on_delete=django.db.models.deletion.CASCADE, to='eyetracking.Graph'),
        ),
    ]
