# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-12 21:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eyetracking', '0013_auto_20160312_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default=datetime.datetime(2016, 3, 12, 21, 55, 53, 37316, tzinfo=utc), max_length=128),
            preserve_default=False,
        ),
    ]
