# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-28 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eyetracking', '0013_auto_20160328_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gathereddata',
            name='graph',
        ),
        migrations.DeleteModel(
            name='Graph',
        ),
    ]
